image: Visual Studio 2019
configuration: Release

environment:
  matrix:
  - arch: x64
  - arch: ARM64

before_build:
  - mkdir build
  - cd build
  - cmake .. -A %arch%

build:
  project: build/hwy.sln
  verbosity: minimal

artifacts:
- path: build\*\Release\*.exe
